@startuml
title State Diagram Applicazione

[*] --> Acceso: accensione

state Acceso {
    state "Richiesta Eventi" as RichiestaEventi
    state "Notifica Utente" as NotificaUtente
    state "Sonno" as Sonno

    [*] -right-> RichiestaEventi

    RichiestaEventi: richiedi eventi
    RichiestaEventi: calcola differenze
    RichiestaEventi --> Sonno: non ci sono previsoni nuove
    RichiestaEventi -right-> NotificaUtente: ci sono previsioni nuove

    NotificaUtente: do/ notifica l'utente
    NotificaUtente --> Sonno

    Sonno: do/ aspetta 10 secondi
    Sonno --> RichiestaEventi

    --

    state "Aspetto Richiesta" as AspettoRichiesta
    state "Mostra Dati" as MostraDati

    [*] -right-> AspettoRichiesta

    AspettoRichiesta: aspetta la richesta di ricerca d'utente
    AspettoRichiesta -right-> MostraDati: utente effetua ricerca

    MostraDati: effettua ricerca
    MostraDati: mostra dati all'utente
    MostraDati -left-> AspettoRichiesta
}

Acceso --> [*]: spegnimento
@enduml
