@startuml
title State Diagram Sorgente

[*] --> Acceso: accensione

state Acceso {

    state "Generazione Previsioni" as GenPrev
    state "Aggiorna: Previsto -> Rientrato" as AggPrevCanc
    state "Aggiorna: InCorso -> Avvenuto" as AggCorAvv
    state "Sonno di Generazione delle Previsioni" as SonnoGen

    [*] --> GenPrev

    GenPrev: genera le previsioni per le prossime 24 ore
    GenPrev --> AggPrevCanc: Ci sono eventi previsti scaduti
    GenPrev --> AggCorAvv: Non ci sono eventi previsti scaduti,\nma ci sono eventi in corso scaduti
    GenPrev --> SonnoGen: Non ci sono eventi scaduti

    AggPrevCanc: Cambia lo stato degli eventi previsti scaduti in cancellati
    AggPrevCanc --> AggCorAvv: Ci sono eventi in corso scaduti
    AggPrevCanc --> SonnoGen: Non ci sono eventi in corso scaduti

    AggCorAvv: Cambia lo stato degli eventi in corso scaduti in avvenuti
    AggCorAvv --> SonnoGen

    SonnoGen: do/ aspetta 5 secondi
    SonnoGen -> GenPrev

    --

    state "Controllo Previsioni Urgenti" as ConPrevUrg
    state "Invio Eventi Urgenti" as InvioEvtUrg
    state "Sonno di Previsioni Urgenti" as SonnoPrevUrg

    [*] --> ConPrevUrg

    ConPrevUrg: controllo lista previsioni eventi
    ConPrevUrg --> InvioEvtUrg: ci sono previsioni urgenti
    ConPrevUrg --> SonnoPrevUrg: non ci sono previsioni urgenti

    InvioEvtUrg: do/ invio eventi urgenti al sistema centrale
    InvioEvtUrg: do/ tolgo previsioni immutabili
    InvioEvtUrg --> SonnoPrevUrg

    SonnoPrevUrg: do/ aspetta 5 secondi
    SonnoPrevUrg --> ConPrevUrg

    ---

    state "Invio Previsioni" as InvPrev
    state "Sonno di Previsioni" as SonnoPrev

    [*] --> InvPrev

    InvPrev: Invio previsioni al sistema centrale
    InvPrev --> SonnoPrev

    SonnoPrev: do/ aspetta 4 ore
    SonnoPrev --> InvPrev

}

Acceso --> [*]: spegnimento
@enduml
