@startuml
title State Diagram Applicazione

[*] --> Acceso: accensione

state Acceso {
    [*] --> RicNot
    state "Richiesta Notifiche" as RicNot
    RicNot: richiedi notifiche

    RicNot --> Sonno: non ci sono notifiche
    Sonno: do/ aspetta 10 secondi

    RicNot -right-> RicNuo: notifiche nuove
    state "Notifice Nuove" as RicNuo
    RicNuo: do/ notifica l'utente

    RicNuo --> Sonno

    Sonno --> RicNot

    --

    [*] -right-> AspRic
    state "Aspetto Richiesta" as AspRic

    AspRic --> RicRic: utente effetua ricerca
    state "Richiesta Ricerca" as RicRic
    RicRic: do/ richiedi dati di ricerca

    RicRic --> AspRic: cancella ricerca

    RicRic -right-> MoDa
    state "Mostra Dati" as MoDa
    MoDa: mostra dati all'utente

    MoDa --> AspRic: indietro
}

Acceso --> [*]: spegnimento
@enduml
