* Protezione Civile

  Protezione Civile è un sistema che permette di allertare gli utenti sui
  disastri naturali.

  È composto da 3 applicativi che comunicano fra di loro:

** CivilProtectionSource
   Gestisce le informazioni inviate dai sensori (che nel nostro caso sono
   generate pseudo-casualmente) e invia previsioni (ed eventi in corso) al
   sistema centrale. Possono esserci da 1 a N source.

** CivilProtectionServer
   Si occupa di immagazzinamento dei dati spediti dai vari source nel DB e
   dell'invio di tali dati all'utente. Può esistere una sola istanza di server.

** CivilProtectionUser
   È l'applicativo usato dai cittadini che è composto da un'interfaccia grafica
   e permette di: visualizzare i dati nella home (*Allarmi in Evidenza* e
   *Prossimi allarmi nei tuoi cap*). È anche possibile effettuare una ricerca
   sugli eventi e gestire i cap preferiti.

* How to launch
  1) Avviare Java/server.bat
  2) Attendere affinché venga visualizzato "Server is running".
  3) Avviare N volte Java/source.bat.
  4) Avviare Java/user.bat

* Makefile
  Attraverso il makefile è possibile compilare l'intero progetto.

  /Requisiti per Windows/: GitBash, make e CygWin.

  Comandi disponibili:

  #+BEGIN_SRC bash
    make uml
  #+END_SRC

  Crea, nella cartella *UML/target*, i diagrammi in formato *png*, a partire dai
  file *puml* attraverso il software plantUML.

  #+BEGIN_SRC bash
    make all
  #+END_SRC

  =make uml= + build di =common=, =source=, =server= e =user=.

  #+BEGIN_SRC bash
    make uberjar
  #+END_SRC

  Crea dei *jar* indipendenti che contengono all'interno tutte le librerie e
  dipendenze necessarie.

  #+BEGIN_SRC bash
    make clean-uml
  #+END_SRC

  Elimina il contenuto della cartella uml/target

  #+BEGIN_SRC bash
    make clean-java
  #+END_SRC

  Elimina il contenuto delle cartella =java/**/target= e =java/**/bin=.

* Note
  Per velocizzare e simulare il funzionamento del sistema:

  - Il source invia previsioni ogni *20s* (invece di *4h*);
  - Gli eventi generati posseggono *CAP* della provincia di Como;
  - L'utente viene creato settando come cap preferiti i *CAP* della provincia di
    *Como*.
  - Nel database sono presenti gli eventi a partire dal 5 giugno fino al 9
    giugno
