#+TITLE: Protezione Civile
* Da fare
** Quando il client fa il poll, bisogna aggiornare gli stati
#+BEGIN_SRC
if expected_at < now
  if status = "expected"
    status = "canceled"
  else if status = "ongoing"
    status = "occured"
#+END_SRC
** Modalita' generazione previsioni (class diag)
   Gestore previsioni ogni 5 secondi generera' previsioni per le prossime 24
   ore. Sorgente, ogni 4 ore, inviera' semplicemente queste previsioni
   eliminando previsioni passate.
** Modalita' notifiche utente (class diag)
   Utente si terra' una copia della lista delle previsioni. Facendo il polling,
   inviera' una notifica all'utente se trova che ci siano degli aggiornamenti.
** Modalita' di generazione delle previsioni in corsa (class diag)
   Quando viene invocato GeneraPrevisioni, se trova delle previsioni che sono in
   corso, li invia subito, eliminando dalle previsioni24h gli eventi che lo
   riguardavano.
** Decouple SearchFilter and CapListGenerator
   Maybe it would be better to have a separate class CapList with generate()
   method
** add on duplicate key update to storeEvents
