package it.polimi.project14.common;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;

public class SearchFilter implements java.io.Serializable {
    // Autogenerated to check
    private static final long serialVersionUID = 1L;

    private Set<Integer> capList;
    private String type;
    private LocalDateTime expectedAt;

    static HashMap<String, HashMap<String, HashSet<Integer>>> caps;

    static {
        // Inizialize caps structure first time that a SearcFilter object is
        // initzialized with all caps value from a file
        String currMunicipality = "";
        String currProvince = "";
        HashSet<Integer> currMunicipalityCapList = new HashSet<>(0);
        HashMap<String, HashSet<Integer>> currMunicipaliesCapsMap = new HashMap<>(0);

        BufferedReader csvReader = null;
        try {
            csvReader = new BufferedReader(new FileReader("provincia_comune_cap.csv"));

            try {
                String row;
                while ((row = csvReader.readLine()) != null) {
                    String[] data = row.split(",");

                    if (data[1] != currMunicipality && currMunicipality != null) {
                        currMunicipaliesCapsMap.put(data[1], currMunicipalityCapList);
                        currMunicipaliesCapsMap.clear();
                        currMunicipality = data[1];
                    }

                    if (data[0] != currProvince && currProvince != null) {
                        caps.put(data[0], currMunicipaliesCapsMap);
                        currProvince = data[0];
                    }

                    currMunicipalityCapList.add(Integer.parseInt(data[3]));

                }
            } catch (NumberFormatException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            } catch (IOException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }

        } catch (FileNotFoundException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();

        } finally {
            if (csvReader != null) {
                try {
                    csvReader.close();
                } catch (IOException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        }
    }

    public void SetCapList(Set<Integer> capList) {
        this.capList = capList;
    }

    public Set<Integer> GetCapList() {
        return this.capList;
    }

    public void SetType(String type) {
        this.type = type;
    }

    public String GetType() {
        return this.type;
    }

    public void SetexpectedAt(LocalDateTime expectedAt) {
        this.expectedAt = expectedAt;
    }

    public LocalDateTime GetExpectedAt() {
        return this.expectedAt;
    }

    public void GenerateCapList(String province, String municipality) {
        capList.clear();
        capList.addAll(caps.get(province).get(municipality));
    }
}