@startuml
title Deployment Diagram

node Sorgente  [
<b>Sorgente
{JVM}

---
ProtezioneCivileSorgente.jar
]

node AppMobile[
<b>Applicazione Mobile
{JVM}

---
ProtezioneCivileClient.jar
]

node Server {
    node Server [
    <b>AppServer
    {JVM}

    ---
    ProtezioneCivileServer.jar
    ]

    database DB [
    <b>SQLite
    ]
}

Sorgente -- Server : RMI\nTCP/IP
AppMobile -- Server : RMI\nTCP/IP
Server -- DB : \lJDBC
Server .(0. DB :  "  DBMS SQL"
@enduml