@startuml
title Object Diagram
object currPrevisioniATempo {
    previsione24H = {EventoTerr, Evento1}
    timer = currTimer
}

object currSorgente {
    id = 100
    timer = currTimer
}

object currServer {
    JDBCurl = "jdbc:sqlite:civil_protection.db"
}

object currUtente {
    capPreferiti = {"91026", "22100"}
    GestoreNotifica = currNotificatoreATempo
}

Object "risultatoRicerca: Set<Evento>" as risultatoRicerca

object filtroRicerca {
    caps = {22100, 22200}
    tipo = "terr"
    massimoPericolo = no
    previstoDal = "8/06/2020 00:00"
    previstoAl = "8/06/2020 24:00"
}

object currNotificatoreATempo {
    utente = currUtente
    notificatoreGUI = currGUI
    timer = currTimer
}

Object currGUI {
    utente = currUtente
}

currSorgente -- currPrevisioniATempo
currSorgente - currServer
currServer - currUtente
currUtente -- filtroRicerca
currUtente -- risultatoRicerca
currUtente -- currNotificatoreATempo
currUtente - currGUI
currGUI -- currNotificatoreATempo
@enduml