@startuml
title Package Diagram
package source {
    interface IGestorePrevisioni<<interface>> 

    class GestorePrevisioni 

    class Sorgente 

    Sorgente -[hidden]- IGestorePrevisioni
    IGestorePrevisioni -[hidden]- GestorePrevisioni
}

package server{
    interface IServer<<interface>> 

    class Server 

    Server -[hidden]- IServer
}

Sorgente .> IServer

package user {
    class Utente 

    interface IGestoreNotifica 
    
    class GestoreNotifica 

    Utente -[hidden]- IGestoreNotifica
    IGestoreNotifica -[hidden]- GestoreNotifica
}

Utente ..> IServer

package common {

    enum StatoEvento 

    class Evento<<dataType>> 

    class ListaEventi <<dataType>>

    ListaEventi -[hidden]- Evento
    Evento -[hidden]- StatoEvento

    class FiltroRicerca 

    class ListaCAP <<dataType>>

    FiltroRicerca -[hidden]- ListaCAP
}

Sorgente ..> ListaEventi
IServer ..> ListaEventi
IServer ..> FiltroRicerca
Utente ..>  ListaEventi
Utente ..>  FiltroRicerca

'Layout only
hide empty members
skinparam classAttributeIconSize 0
ListaEventi -[hidden] FiltroRicerca
GestorePrevisioni -[hidden]-- StatoEvento
Server .[hidden].> ListaEventi
Utente .[hidden].> FiltroRicerca
@enduml