@startuml
title Package Diagram
package source {
    interface Previsioni<<interface>>

    class PrevisioniATempo

    class Sorgente

    Sorgente -[hidden]- Previsioni
    Previsioni -[hidden]- PrevisioniATempo
}

package server{
    class ArchivioEventiImpl
}

package common {
    interface ArchivioEventi<<interface>>

    enum StatoEvento

    class Evento

    Evento -[hidden]- StatoEvento

    class FiltroRicerca

    ArchivioEventi -[hidden]- Evento
    Evento -[hidden]> FiltroRicerca
}

package user {
    class Utente

    interface Notificatore

    class NotificatoreATempo

    class Caps

    Utente -[hidden]- Notificatore
    Notificatore -[hidden]- NotificatoreATempo
    NotificatoreATempo -[hidden]- Caps

    package gui {

    }

    gui -[hidden]- Utente
}

source .> common
source .> server
server ..> common
user .> common
user .> server

'Layout only
hide empty members
skinparam classAttributeIconSize 0
Sorgente -[hidden]> StatoEvento
@enduml