@startuml
skinparam packageStyle rectangle
actor "Sorgente"
actor Utente

rectangle "Sistema di Allerta" {
    actor "Sistema Centrale" as SisCentrale
    Sorgente - (Aggiornare dati previsione)
    Sorgente - (Inviare dati eventi in corso)

    SisCentrale -- (Aggiornare dati previsione)
    SisCentrale -- (Inviare dati eventi in corso)
    SisCentrale -- (Inviare dati richiesti)
    SisCentrale -- (Inviare notifiche per eventi di interesse dell'utente)
    SisCentrale -- (Invia allarmi in evidenza)

    (Inviare notifiche per eventi di interesse dell'utente) - Utente
    (Invia allarmi in evidenza) - Utente
    (Inserire Cap preferiti) - Utente
    (Effettuare richerche) - Utente

    together {
        (Effettuare richerche) <.. (Scegli istante temporale) : extends
        (Effettuare richerche) <.. (Scegli tipo) : extends
        (Effettuare richerche) <.. (Scegli Cap) : extends
    }

    (Scegli Cap) <|- (Autogenera Cap)
    (Scegli Cap) <|- (Inserisce Cap)

    together {
        (Autogenera Cap) .> (Seleziona provincia) : extends
        (Autogenera Cap) .> (Seleziona comune) : extends
    }
    (Inserire Cap preferiti) .> (Scegli Cap) : include
    (Effettuare richerche) .> (Inviare dati richiesti) : include
}

'Layout only
SisCentrale -[hidden]- Sorgente
SisCentrale -[hidden] Utente
(Inviare dati eventi in corso) -[hidden]- (Aggiornare dati previsione)
(Inviare dati eventi in corso) -[hidden] (Inviare dati richiesti)
(Inviare dati richiesti) -[hidden] (Inviare notifiche per eventi di interesse dell'utente)
(Inviare dati richiesti) -[hidden] (Inserire Cap preferiti)
(Inviare notifiche per eventi di interesse dell'utente) -[hidden]- (Inserire Cap preferiti)
(Inserire Cap preferiti) -[hidden]- (Effettuare richerche)
(Scegli Cap) -[hidden] (Scegli tipo)
(Scegli tipo) -[hidden] (Scegli istante temporale)
(Inserisce Cap) --[hidden] (Autogenera Cap)
(Scegli Cap) -[hidden]- (Inserisce Cap)
(Seleziona provincia) --[hidden] (Seleziona comune)
@enduml
