@startuml
title Sequence Diagram Ricerca
actor Utente

Utente -> "Applicazione Mobile": Get Previsioni (Dati Ricerca)
activate "Applicazione Mobile"

"Applicazione Mobile" -> "Sistema Centrale": Get Previsioni
activate "Sistema Centrale"

"Sistema Centrale" -> "Database": Query al Database
activate "Database"

"Database" -> "Sistema Centrale": Risultato Query
deactivate "Database"

"Sistema Centrale" -> "Applicazione Mobile": Previsioni
deactivate "Sistema Centrale"

"Applicazione Mobile" -> Utente: Previsioni
deactivate "Applicazione Mobile"
@enduml