@startuml
title Deployment Diagram

node Sorgente  [
<b> Sorgente
{OS = Linux/Windows/MacOS}

---
allarmSorgente.jar
]

node AppMobile [
<b> Applicazione Mobile
{OS = Android/IOS}

---
allarmMobile.jar
]

database DB [
<b> DBMS MySQL
]

Sorgente -- DB : JDBC
AppMobile -- DB : JDBC
@enduml