@startuml
title Deployment Diagram

node Sorgente  [
<b>Sorgente
{JVM}

---
allarmSorgente.jar
]

node AppMobile[
<b>Applicazione Mobile
{JVM}

---
allarmMobile.jar
]

frame Server {
    node Server [
    <b>AppServer
    {JVM}

    ---
    allarmServer.jar
    ]
    database DB [
    <b>DBMS SQL
    ]
}

Sorgente -- Server : TCP/IP RMI
AppMobile -- Server : TCP/IP RMI
Server -- DB : JDBC
@enduml