@startuml

partition Sorgente {
	(*) --> ===S1===
	===S1=== --> "Rilevazione Nuovo Evento"
	--> "Elaborazione Dati"
	--> "Inserimento Dati
	in Registro 24h"
	--> if "Continuare Rilevazione"
		--> [true] "Rilevazione Nuovo Evento"
	else
		--> [false] (*top)
	===S1=== --> "Gestione Invio Dati"
	--> if "4h Trascorse" then
		--> [true] "<<Invio Segnale>>\nInvio Previsioni 24h"
	else
		--> [false] "Gestione Invio Dati"
	===S1=== --> "Gestione Invio Evento Corrente"
	--> if "5sec Trascorsi" then
		--> [true] "<<Invio Segnale>>\nInvio Evento Corrente"
	else
		--> [false] "Gestione Invio Evento Corrente"
	
}

partition "Sistema Centrale" {
	"<<Invio Segnale>>\nInvio Previsioni 24h" -[hidden]-> "<<Segnale Ricevuto>>\nRicezione Previsioni"
	--> if "Verificare Variazioni"
		--> [true] "Aggiornamento Database"
	else
		--> [false] (*)
	"Aggiornamento Database" --> (*)
}

@enduml