@startuml

partition Utente {
    (*) --> "Inserimento CAP Preferiti"
}

partition "Applicazione Mobile" {
    "Inserimento CAP Preferiti" -right-> "Memorizzare CAP Preferiti"
    "Memorizzare CAP Preferiti" --> ===S1===
    ===S1=== --> "Formulare Query Previsioni"
    --> "Invio Query Previsioni"
    ===S1=== --> "Formulare Query Allarmi"
    --> "Invio Query Allarmi"
}

partition Sistema {
    "Invio Query Previsioni" -right-> "Eseguire Query Previsioni"
    --> "Invio Risultato Query Previsioni"
    "Invio Query Allarmi" -right-> "Eseguire Query Allarmi"
    --> "Invio Risultato Query Allarmi"
}

partition "Applicazione Mobile" {
    "Invio Risultato Query Previsioni" --> "Ricezione Risposta Query Previsioni"
    --> ===S2===
    "Invio Risultato Query Allarmi" --> "Ricezione Risposta Query Allarmi"
    --> ===S2===
    --> "Visualizza Allarmi e Previsioni"
    --> (*)

    "Invio Query Previsioni" -[hidden]-> "Ricezione Risposta Query Previsioni"
    "Invio Query Allarmi" -[hidden]-> "Ricezione Risposta Query Allarmi"
}

@enduml
